name: Lint and Format

on:
  push:
    branches:
      - main
      - "release/*"
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  ruff:
    name: Lint and Format (Ruff)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install Ruff
        run: pip install ruff==0.14.1

      - name: Check Linting
        run: ruff check .

      - name: Check Formatting
        run: ruff format --check .

  eslint:
    name: Lint and Format (ESLint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "20"

      - name: Install ESLint
        run: npm install -g eslint@9.15.0 eslint-config-prettier@9.1.0

      - name: Check Linting and Formatting
        run: eslint "**/*.{js,jsx}" --max-warnings 0
